### ISSUE TITLE
Features too shiny

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/Beyond-All-Reason#1777] opened 2023-05-16 17:56 UTC
https://github.com/beyond-all-reason/Beyond-All-Reason/commit/44ce9a2
This commit causing features being shiny on nvidia GPUs
![screen01447](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/116835691/bb8f53e7-126c-4b43-a2fe-e7eedd27411b)
![screen01446](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/116835691/4f72e90d-95c2-4f51-a472-c0bb0795475a)

**Comment by SethDGamre** [comment] 2024-09-29 02:39
appears to be a duplicate of https://github.com/beyond-all-reason/Beyond-All-Reason/issues/1736

**Comment by hihoman23** [comment] 2024-09-29 09:05
Closing duplicate

**Closed by hihoman23** 2024-09-29 09:05 UTC
