### ISSUE TITLE
Bug: bots start with high construction priority

### ISSUE THREAD

**Issue by yuyaryshev** [beyond-all-reason/Beyond-All-Reason#590] opened 2021-11-21 07:58 UTC
All construction robots start with high priority. Which is strange: how do I quickly set higher priority then?
Suggestions: make 'normal' priority default

**Comment by Beherith** [comment] 2021-11-23 22:42
Dont they inherit their priority from their factory?

**Comment by WatchTheFort** [comment] 2021-11-23 22:45
> Dont they inherit their priority from their factory?

That's an issue, because priority is a stateful order that applies to the factory itself, unlike the other stateful orders that its units inherit.

**Comment by KyleAnthonyShepherd** [comment] 2023-08-31 04:28
![image](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/44480662/f0209368-7af4-4364-8298-c4cfdd84de83)
Option exists in-game to set constructor priority. 
Closing issue, as the issue is not fully specified

**Closed by KyleAnthonyShepherd** 2023-08-31 04:28 UTC
