### ISSUE TITLE
Empty AllyTeam (Startbox without a team) causes victory condition to not trigger

### ISSUE THREAD

**Issue by Damgam** [beyond-all-reason/Beyond-All-Reason#778] opened 2022-02-07 00:48 UTC
The 0 units allyteam isn't considered dead i suppose.

**Comment by 6AKU66** [comment] 2022-02-07 00:57
Duplicate of https://github.com/beyond-all-reason/Beyond-All-Reason/issues/563?

**Comment by sprunk** [comment] 2022-02-07 11:04
Duplicate of #563

**Closed by sprunk** 2022-02-07 11:04 UTC

**Comment by 6AKU66** [comment] 2022-02-07 11:12
P.S I will rename my ticket, Damgam's title more good than mine.
