### ISSUE TITLE
Structures can be build inside Cortex experimental gantry

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#786] opened 2022-02-12 04:47 UTC
https://youtu.be/JrHOsr2pb-Y
![corgant mp4_snapshot_00 12_ 2022 02 12_07 45 55](https://user-images.githubusercontent.com/89547444/153696992-19293c0c-f256-4195-af2b-86e3c1322ce7.jpg)

**Comment by WatchTheFort** [comment] 2022-02-12 05:54
This is a problem with all factories, since construction yardmaps count as completely open, allowing move orders and construction orders to be issued inside.

**Comment by WatchTheFort** [comment] 2022-02-15 04:26
Duplicate of #612

**Closed by WatchTheFort** 2022-02-15 04:26 UTC
