### ISSUE TITLE
Air fighters SlowUpdate Lag

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1270] opened 2022-09-19 09:08 UTC
I think there's space for optimization for air fighters, since raptors fighters don't cause so much lag.
https://youtu.be/7nLvWeVs2Io
https://youtu.be/JIfJ1gaQOSc

**Comment by Beherith** [comment] 2022-09-19 09:18
Dunno what is done in slowupdate, but my suspicion lies in the gadget unit_continuous_aim.lua

e.g.

	[UnitDefNames.armvang.id] = 2,
means that armvang will aim every 2 frames. 
Please try this test with the respective fighters changed back to every 15 frames, which is the default.

**Comment by Beherith** [comment] 2022-09-19 09:18
oh wait fighters dont reaim. odd.

**Comment by Beherith** [comment] 2022-10-02 17:12
This one has not let me rest for a while, and I would be very interested in how this test changes with the new luarules fightertest implementation. The difference between armvang and chicken fighter is striking. Could it be caused by airjets? This would ideally be validated with luaui off.

**Comment by 6AKU66** [comment] 2022-10-02 17:18
Luaui off make no difference.

**Comment by 6AKU66** [comment] 2022-10-11 15:16
avoidfriendly = true doing that

**Comment by Ruwetuin** [comment] 2022-10-24 14:33
ehhhh armvang is the vanguard, you're confused with corveng

> Dunno what is done in slowupdate, but my suspicion lies in the gadget unit_continuous_aim.lua
> 
> e.g.
> 
> ```
> [UnitDefNames.armvang.id] = 2,
> ```
> 
> means that armvang will aim every 2 frames. Please try this test with the respective fighters changed back to every 15 frames, which is the default.

armvang is the vanguard, I think you're confused with corveng

**Comment by Ruwetuin** [comment] 2022-10-24 14:49
> avoidfriendly = true doing that

disabled avoidfriendly (safe to do since collidefriendly was already false)

fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/d1473b2958bd4b7dfccd6fc5bd1a3c2c78ba42f6

**Closed by Ruwetuin** 2022-10-24 14:49 UTC
