### ISSUE TITLE
Energy in scenario goes in negatives and pre-placed e-stores doesn't hold energy

### ISSUE THREAD

**Issue by lolsteamroller** [beyond-all-reason/Beyond-All-Reason#820] opened 2022-02-21 22:13 UTC
![image](https://user-images.githubusercontent.com/7465747/155032047-fe80d5fc-6a06-4087-a1a7-aa350d0dee89.png)

**Repro:**

1 - Load scenario "Keep your secrets"
2 - Upon loading you will see max storage @ ~8K
3 - After game starts, the storage is now 1K (energy)
4 - Make some rezzbots from Bot Lab
5 - Go and reclaim the original energy storage located in the half-island next to you
6 - The energy is now -5k

**Comment by PtaQQ** [comment] 2022-09-27 17:19
Fixed with [dee595c](https://github.com/beyond-all-reason/BYAR-Chobby/commit/dee595c0505ada05ba7bb6edd5ef6a7b6dc656e6)

**Comment by WatchTheFort** [comment] 2022-09-27 19:49
> Fixed with [dee595c](https://github.com/beyond-all-reason/BYAR-Chobby/commit/dee595c0505ada05ba7bb6edd5ef6a7b6dc656e6)

Is the root cause bug itself fixed? Where buildings placed as part of the loadout don't actually apply their effects. @Beherith know more about the root cause.

**Comment by Beherith** [comment] 2022-09-28 14:08
No, the root cause is not fixed, this is just a workaround

**Comment by KyleAnthonyShepherd** [comment] 2023-08-31 05:36
Appears the PR fixing the root cause has been merged in, closing issue

**Closed by KyleAnthonyShepherd** 2023-08-31 05:36 UTC
Labels: bug
