### ISSUE TITLE
Scavenger player unable to start building

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#715] opened 2022-01-10 20:09 UTC
https://youtu.be/Pd6UzEtqTlI

**Comment by Damgam** [comment] 2022-01-10 21:49
That might have something to do with priority widget.

**Comment by Beherith** [comment] 2022-01-10 22:12
Is the con pulling resources?

**Comment by KyleAnthonyShepherd** [comment] 2023-08-31 05:04
Unable to reproduce, a scav corca is building fine, closing

**Closed by KyleAnthonyShepherd** 2023-08-31 05:04 UTC
