### ISSUE TITLE
Openal is missing from appimage

### ISSUE THREAD

**Issue by bkchr** [beyond-all-reason/Beyond-All-Reason#123] opened 2020-11-23 12:29 UTC
Hey, I'm using the appimage on Linux, but the openal library is missing from the image. 

Is there any script that builds the appimage? I would like to contribute the required changes to add the missing library.

**Comment by gajop** [comment] 2020-11-23 23:21
This is basically a duplicate of https://github.com/gajop/spring-launcher/issues/30 . 
Spring (our engine) doesn't distribute libraries for Linux, where users/distributions are expected to supply them.

It would of course be ideal to supply them ourselves, here's how it's currently being done for pr-downloader (download system) DLLs (mostly for Windows):
https://github.com/gajop/spring-launcher/tree/master/bin

I'm not sure this can be solved by just placing these libraries there. Spring would need to somehow be instructed to dynamically link with that. Spring is currently located in the engine/engine_version directory. You can take a look at the windows build https://springrts.com/dl/buildbot/default/maintenance/104.0.1-1553-gd3c0012/ to see how these libraries are included 

The full build process can be seen https://github.com/gajop/spring-launcher-backend/tree/master/src/builder

**Comment by bkchr** [comment] 2020-11-24 08:40
> Spring (our engine) doesn't distribute libraries for Linux, where users/distributions are expected to supply them.

Yeah I understand this, but the idea of appimages is that they contain all the required libraries to make the program run. There is some list of libraries that needs to be provided by a system that runs an appimage. However `openal` seems to be not in the list of provided libraries.

Nevertheless, thank you for your answer! I will see what I can do.

**Comment by tobias47n9e** [comment] 2021-09-03 15:36
@bkchr I also noticed that the AppImage is missing libs on e.g. Ubuntu 21.10 Alpha (at the moment, the Alpha might still change some standard libs). Would be using the Flatpak (https://flathub.org/apps/details/info.beyondallreason.bar) be a solution for you? It's better sandboxes than AppImage and should come with all required libraries.

**Comment by bkchr** [comment] 2021-09-04 18:33
@tobias47n9e ty! I will try it the next time :)

**Comment by Beherith** [comment] 2022-02-21 14:16
Indeed, use the appimage, thanks tobias!

**Closed by Beherith** 2022-02-21 14:16 UTC
