### ISSUE TITLE
Construction aircraft dose not help the other one when I guard it.

### ISSUE THREAD

**Issue by TheDeinosuchus** [beyond-all-reason/Beyond-All-Reason#2618] opened 2024-02-15 13:22 UTC
### Description

I tell one of my cortex construction aircraft to make a field of windturbines. Then I tell another cortex construction aircraft to guard the first one. The second cortex construction aircraft helps the first one for a little bit. But then it stops and does nothing.

### Expected Behaviour

The second cortex construction aircraft should help the first one until I order it to stop doing that.

### Actual Behaviour

Instead the second cortex construction aircraft helps the first one for a little bit. But then it stops and does nothing.

### Other

On Linux (Ubuntu) computer (PC).

**Comment by hihoman23** [comment] 2024-09-29 17:48
I think this is related to building at the edge of a map, when the building plane starts a new building while it is outside the borders and the other planes then start ignoring the other one

**Comment by hihoman23** [comment] 2024-09-29 17:49
Another related issue is that aircraft outside the map edges can’t be given a guard command

**Comment by hihoman23** [comment] 2024-09-29 19:54
Actually duplicate of #763

**Closed by hihoman23** 2024-09-29 19:54 UTC
Labels: Bug
