### ISSUE TITLE
Setting "Guard" or any other right click operation on an aircraft outside the map fails.

### ISSUE THREAD

**Issue by xyz32** [beyond-all-reason/Beyond-All-Reason#617] opened 2021-12-12 15:19 UTC
Setting building way-point onto a constructor aircraft will fail to send the new unit there every time the target floats outside the map (it building at the edge of the map).
Steps to repro:
1. Set an aircraft builder to build at the edge of the map.
2. While the aircraft is floating outside the map assign another unit to "Guard" this constructor by right-clicking on it.
Observe behaviour: Even though the Guard button on the UI will flicker, the order is not executed.

**Comment by KyleAnthonyShepherd** [comment] 2023-08-31 04:33
Somewhat intentional, to prevent tricks of sending aircraft way outside the bounds of the map, but preserving quality-of-life things like not silently dropping guard commands on a con aircraft that briefly leave the map would be nice

**Comment by KyleAnthonyShepherd** [comment] 2023-08-31 05:25
Closing this issue, as this is duplicate of [this ](https://github.com/beyond-all-reason/Beyond-All-Reason/issues/763) and that has more discussion

**Closed by KyleAnthonyShepherd** 2023-08-31 05:25 UTC
Labels: bug
