### ISSUE TITLE
Burning trees can (only) be reclaimed via area reclaim command

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#2386] opened 2023-12-09 12:47 UTC
Burning trees can be reclaimed via area reclaim command, but cannot be reclaimed with non-area reclaim command. I don't know if reclaiming burning trees is intended feature or not.
https://youtu.be/ZaVFHxEzfLs

**Comment by SethDGamre** [comment] 2024-09-29 05:05
I was able to recreate this

**Comment by SethDGamre** [comment] 2024-09-29 05:07
duplicate of https://github.com/beyond-all-reason/Beyond-All-Reason/issues/1513

**Comment by hihoman23** [comment] 2024-09-29 08:09
Closing duplicate

**Closed** 2024-09-29 08:09 UTC
