### ISSUE TITLE
Front-Queueing Units in Factories Differs in Behavior Depending on Repeat State

### ISSUE THREAD

**Issue by Brian-Catcow-B** [beyond-all-reason/Beyond-All-Reason#3155] opened 2024-06-12 16:50 UTC
### Description

Front queueing units to build in a factory doesn't always work the same way

### Expected Behaviour

It should always do the same thing no matter what the factory's settings are

### Actual Behaviour

If Repeat is on, then front queueing via space+m1 (on a unit to queue) will place that unit "next in line" after the current unit

If Repeat is off, then front queueing will stop the current unit from building and will start the newly front queued unit immediately

### Reproduction steps

Build a factory and rest front queueing with Repeat on, see what happens, then try again with Repeat off. Each time with unit(s) queued. 

### Other

I suggest that the fix involves game settings where the user can set the factory front queueing behavior between "after current project" and "right away" (maybe having a third option "right away if Repeat Off", which is current behavior), and also have that option for other things like front queueing commands on constructors or other units. Those should be separate settings though because different behavior could be wanted in the different cases. For instance, if a player runs out of energy, front queueing a solar collector with their commander should start that right away, but with T1 spam from a factory, the factory might as well finish the current tick or grunt before creating a rez bot, for example. 

To whomever works on this, I've also noticed that factory front queueing the same thing as the current unit being built restarts the work on the unit, which makes no sense. So if you can fix that too, great!

**Comment by StanczakDominik** [comment] 2024-06-12 16:52
Duplicate of #1522 ?

**Comment by sprunk** [comment] 2024-06-12 16:59
Duplicate of #1522

**Comment by sprunk** [comment] 2024-06-12 16:59
> To whomever works on this, I've also noticed that factory front queueing the same thing as the current unit being built restarts the work on the unit, which makes no sense. So if you can fix that too, great!

This part is a duplicate of #3121 as well

**Closed by sprunk** 2024-06-12 16:59 UTC
Labels: Bug
