### ISSUE TITLE
legion adv aircraft plant not building despite having queue set

### ISSUE THREAD

**Issue by springraaar** [beyond-all-reason/Beyond-All-Reason#1079] opened 2022-07-12 13:56 UTC
legion adv aircraft plant not building despite having 10 legion flying fortresses queued 
happened at about 43 min in for player raaar (southwest)
I noticed a few min later and tried to set/clear wait to see if it fixed, it didn't so i built another factory
about 50min in i tried clearing queue and resetting it and it fixed the issue

(replay in attachment)

note : I've had this issue with adv aircraft factories on Metal factions (engine 105.0) as well and in some cases resetting the queue didn't fix the issue (may not be relevant here)

[20220712_020604_All That Glitters v1_105.1.1-966-g597222f BAR105_43min_raaar_advairlab_stop_building.sdfz.zip](https://github.com/beyond-all-reason/Beyond-All-Reason/files/9093609/20220712_020604_All.That.Glitters.v1_105.1.1-966-g597222f.BAR105_43min_raaar_advairlab_stop_building.sdfz.zip)

**Comment by springraaar** [comment] 2022-07-12 13:57
the attached file is a regular .sdfz, I added the ".zip" to be able to upload to github

**Comment by Zecrus2** [comment] 2022-07-12 15:17
The legion adv aircraft plant currently has the same model and script as the cor adv aircraft plant, so the building shouldn't be the problem.  Maybe the issue is that the flying fortress dips down before slowly taking off, and it blocked the air plant's pad for too long for it to properly start the next unit.  I'll see if I can replicate it in single player

**Comment by lhog** [comment] 2022-07-12 17:23
Would love to see that issue reproduced in an artificial environment.

**Comment by SethDGamre** [comment] 2024-10-06 02:18
This is an ancient issue. Furthermore it should have been resolved with the exit only yardmap rework.

**Closed by SethDGamre** 2024-10-06 02:18 UTC
Labels: Bug
