### ISSUE TITLE
Selection of enemy units should be allowed without Godmode

### ISSUE THREAD

**Issue by zxbc** [beyond-all-reason/Beyond-All-Reason#1842] opened 2023-06-07 23:12 UTC
So that unit tool tip can persist for easier reading. Whether multiple units can be selected is subject to debate, but I think at least single selection should be allowed.

**Comment by sprunk** [comment] 2023-06-29 15:34
Belongs in the engine repo where it is a duplicate of beyond-all-reason/spring#567

**Closed by sprunk** 2023-06-29 15:34 UTC
