### ISSUE TITLE
Kolmogorov map is broken for Scavengers

### ISSUE THREAD

**Issue by EldoreiJK** [beyond-all-reason/Beyond-All-Reason#287] opened 2021-05-04 22:17 UTC
We played Kolmogorov map with a friend vs Scavengers, and the map was completely broken. We weren't able to get our amphibious units on the water, while Scavs were able to send them from water to our land bases. Our ships wouldn't move when built in shipyards, but their ships attacked us without a problem. While the map may seem OK for PvP, the water causes a lot of issues with Scavs.

**Comment by icexuick** [comment] 2021-05-04 22:29
It's an old map, which can give very interesting gameplay.
But it's marked as 'classic' which means it's not updated/remade for BAR, with not only improved graphics but also fixed issues.
So check which maps are "certified" they have 99% of working well and as intended.

Chances are pretty good for Kolmogorov to get an update someday.

**Comment by sprunk** [comment] 2021-05-05 21:33
Kolmogorov has a typemap which prevents movement in the water (except air units) so player units being unable to move is "intended" (at least from the map designer's point of view). Unsure why Scavs wouldn't obey the typemap though.

**Comment by Beherith** [comment] 2022-02-21 14:23
Kolmogorov has been remade, no more nasty typemap

**Closed by Beherith** 2022-02-21 14:23 UTC
