### ISSUE TITLE
Add a delay for spectators

### ISSUE THREAD

**Issue by fupsx** [beyond-all-reason/Beyond-All-Reason#2627] opened 2024-02-17 11:02 UTC
### Description

Add a delay for spectators watching a match. Mybe as an option in a gamelobby.

### Why?

Prevent players from cheating. 

### What area of the game does this feature request pertain?

Gameplay

**Comment by sprunk** [comment] 2024-02-17 14:57
Duplicate of beyond-all-reason/spring#706

**Closed by sprunk** 2024-02-17 14:57 UTC
Labels: Enhancement, Awaiting GDT Approval
